baseURL = "http://example.org/"
languageCode = "en-us"
title = "bluesky641"
theme = "hugo-theme-docport"

[params]
	description = "这是bluesky641的博客"
	themeColor = "#d35050"

[[params.social]]
  name = "github"
  url = "https://github.com/bluesky641"

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"
